export const players = [
  { pseudo: 'Mouss', score: 650, favoriteGame: 'Scrabble', description: 'Imbattable' },
  { pseudo: 'Nico', score: 300, favoriteGame: 'Monopoly', description: 'Property trading game' },
  { pseudo: 'MarioMan', score: 180, favoriteGame: 'Chess', description: 'Strategy board game' },
  { pseudo: 'Toto', score: 400, favoriteGame: 'Ticket to Ride', description: 'Train adventure game' },
  { pseudo: 'CyberPlayer', score: 500, favoriteGame: 'Bataille', description: 'Expert en stratégie' },
  { pseudo: 'GamerPro', score: 320, favoriteGame: 'Course de voitures', description: 'Amateur de vitesse' },
  { pseudo: 'RocketGamer', score: 450, favoriteGame: 'Tir à la première personne', description: 'As des jeux de tir' },
  { pseudo: 'GameMaster', score: 600, favoriteGame: 'Dungeons & Dragons', description: 'Maître du jeu de rôle' },
  { pseudo: 'PuzzleSolver', score: 280, favoriteGame: 'Puzzle', description: 'Résolveur de casse-tête' },
  { pseudo: 'DiceRoller', score: 420, favoriteGame: 'Yahtzee', description: 'Lanceur de dés expert' },
  { pseudo: 'WordSmith', score: 380, favoriteGame: 'Scrabble', description: 'Maître des mots croisés' },
  { pseudo: 'CardShark', score: 340, favoriteGame: 'Poker', description: 'As du bluff' },
  { pseudo: 'BoardGamer', score: 290, favoriteGame: 'Catan', description: 'Seigneur de la stratégie' },
  { pseudo: 'ChessMaster', score: 520, favoriteGame: 'Chess', description: 'Grand maître des échecs' },
  { pseudo: 'WordWhiz', score: 380, favoriteGame: 'Scrabble', description: 'Génie des mots' },
  { pseudo: 'PuzzleGuru', score: 410, favoriteGame: 'Puzzle', description: 'Gourou des casse-tête' },
  { pseudo: 'CardPlayer', score: 360, favoriteGame: 'Poker', description: 'Virtuose des cartes' },
  { pseudo: 'DiceMaster', score: 480, favoriteGame: 'Yahtzee', description: 'Maître des dés' },
];
